name: "Post-Integration: Prerelease"

on: 
  workflow_dispatch:

env:
  # Repository of regression test in format <organization>/<repository>.
  REPOSITORY: "sepulsa/sepulsa01"
  
jobs:
  test1:
    runs-on: ubuntu-20.04
    
    steps:
      - name: print semua env variable 1
        run: |
          echo "job test 1"
          printenv
          
  test2:
    runs-on: ubuntu-20.04
    
    steps:
      - name: print semua env variable 2
        run: |
          echo "job test 2"
          printenv
