name: simulasi manual

on: 
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-20.04
    
    steps:
      - name: set environment variable
        run: 
          echo "action_state=feature/bpa001 | cut -d'/' -f 2" >> $GITHUB_ENV
          echo "${{ env.action_state }}"
    
