name: "Restore DB Archive"

on: 
  workflow_dispatch

jobs:
  restoreDB:
    runs-on: ubuntu-20.04
    env:
      dbType: ""
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1
      - name: Prepare Kubeconfig
        env:
          K8S_CLUSTER: "archipelagostaging"
          K8S_CONTEXT: "arn:aws:eks:ap-southeast-1:267475692844:cluster/archipelagostaging"
        run: |
          aws eks update-kubeconfig --name ${K8S_CLUSTER}
          kubectl config current-context
          kubectl config use-context ${K8S_CONTEXT}
          kubectl -n serpul port-forward svc/mongodb-replica-set-svc 27018:27017
      - name: Restore DB Archive
        run: |
          aws s3 cp s3://alterra-proteuscore-mongodump/proteuscore.archive .
          mongorestore --port=27018 --archive=proteuscore.archive
