name: simulasi manual

on: 
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-20.04
    
    steps:
#       - name: set environment variable
#         run: 
#           echo "action_state=feature/bpa001 | cut -d'/' -f 2" >> $GITHUB_ENV
#             echo "action_state=yellow" >> $GITHUB_ENV
#             echo "${{ env.action_state }}"

      - name: inisiasi
        id: get-id
        run: |
          id=$(echo feature/bpa001 | cut -d '/' -f2)
          echo "::set-output name=id::$id"
      - run: |
          echo "${{steps.get-id.outputs.id}}"
          echo "${github.event_name}"
          
#       - name: Set the value
#         id: step_one
#         run: |
#             echo "action_state=${{steps.get-id.outputs.id}}" >> $GITHUB_ENV
#       - name: Use the value
#         id: step_two
#         run: |
#             echo "${{ env.action_state }}" # This will output 'yellow'
#       - name: print environmnet variable 
#         id: print-env
#        run:
#          printenv
    
